eureka:
  client:
    serviceUrl:
      defaultZone: http:/localhost:9998/eureka
spring:
  cloud:
    gateway:
      routes:
        - id: microservice-projet
          uri: lb://microservice-projet
          predicates:
            - Path=/projet/**
          filters:
            - RewritePath=/projet/(?<path>.*), /$\{path}
